### ISSUE TITLE
[DATA] CVE-2021-0936 is possibly Android specific

### ISSUE THREAD

**Issue by DerDakon** [nluedtke/linux_kernel_cves#242]
**Change Type Requested**
Remove or Update

**CVE id number**
CVE-2021-0936

**Additional context**
I can't find neither the file f_accessory.c nor the specified function ```acc_read``` anywhere in the kernel source of current master branch or 4.9 stable, or anywhere in between. I suspect this is an Android addition and only affects their kernel.

**Comment by jbmaillet** [comment]
I would second that: from [https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-0936](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-0936)

- The only references are from an Android security bulletin.
- The assigning CNA is Android (associated with Google Inc. or Open Handset Alliance).
- The file itself, from the Android device source trees I work on, is for a "Gadget Function Driver for Android USB accessories", option CONFIG_USB_F_ACC
- As for the NVD the issue is tagged as a vendor advisory, and the only impacted CPE is o:google:android, and it's the only one on the history of the analysis. So I don't get how it landed here.

On the other hand, I'd rather have a handful of false positives like this than an incomplete status.
